sudo aptitude install build-essential automake cmake patch git-core php5-cli php5-dev libpcre3-dev -y
git clone https://github.com/libgit2/libgit2.git
cd libgit2
mkdir build
cd build
cmake ..
cmake --build .
sudo cmake --build . --target install
cd ../../


git clone https://github.com/libgit2/php-git.git
cd php-git
phpize
./configure
make test
